name: Test Cron

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:        # optional manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print timestamp
        run: echo "Cron workflow ran at $(date)"
